### ISSUE TITLE
Advance styles

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ideas#10]
SLD are too tightly coupled to WMS
Sharing of styles

**Comment by rcasscslt** [comment]
Possibly look at opening up SE on two fronts :

**Comment by prushforth** [comment]
Think about how to leverage CSS for spatial info, as SVG does for vector graphics and the respective roles of SLD / SE and CSS.

**Comment by rcasscslt** [comment]
Luis, 

What did you mean by sharing of styles? Are you talking about the application of the same style definition to different feature classes , such as the work that Stephane Fellah is doing, or more along the lines of a common way to share and exchange styling information which is probably the "well discussed"  Portrayal catalog for storing, retrieving, versioning etc?

**Comment by bermud** [comment]
@rcasscslt, in the past we have been asked about a repository of styles for a particular domain. For example for aviation? There is no one central place that one can go to get the styles for common features. It is related to the Portrayal Catalog.

And your idea of opening SE is related to this as well. Can we get inspired from other efforts about how to simplify the encoding of styles that can be reused in other environments (other than WMS)?

**Comment by ingosimonis** [comment]
SLD and SE are reviewed in Testbed-14's [Portrayal task](file:///Users/ingosimonis/Dropbox/T14/_CFP/cfp.html#Portrayal).
