### ISSUE TITLE
OpenGIS Harmonization cross-project inititaive

### ISSUE THREAD

**Issue by jodygarnett** [opengeospatial/ideas#120]
The Open Source Geospatial foundation has established a [OpenGIS Harmonization](https://www.osgeo.org/opengis-harmonization/) cross-project initiative to resolve the use of the **org.opengis** java package.

We would like to ask the OGC board to join this as a joint-initiative and share the sponsorship opportunity with OGC members.

Reference:
- https://git.osgeo.org/gitea/osgeo/todo/issues/142

**Comment by jodygarnett** [comment]
This activity has started at the foss4g code sprint, we did not hear back from the OGC board on this activity.

**Comment by jodygarnett** [comment]
This activity has proceeded without your support, this is a disappointing result of attempted collaboration between organizations.

**Comment by ghobona** [comment]
The issue has been resolved.

The announcement is at https://geotoolsnews.blogspot.com/2023/10/geotools-300-released.html
