### ISSUE TITLE
Advance a WCS simple REST API

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ideas#13]
The WCS 2.0 standard allows publication and query of multidimensional data. HTTP POST request are frequent. This tasks will explore developing a simple WCS HTTP API that can support 80% of the most common requests.

The API should support:
  - 3D aviation data
  - Data cubes
  - Common meteorological oceanographic data

Deliverables (maybe advancing a WCS 3.0 simple API):
- Analysis of APIs structure
  -  General APIs
  -  Family of APIs
  -  Controlled vocabularies use
- Data
  -  Multidimensional data (including trajectories)
- Servers
   - WCS 2.0 Server
   - WCS simple API as proxy for the WCS 2.0 server
- Clients (1 or more)  
   - Mobile client that invokes the WCS simple API (SDK mobile developer)
   - Web client that invokes the WCS 3.0 simple API (Javascript library)
   - Other client that invokes the WCS 3.0 simple API 
- Documentation
   - Draft standard document to be submitted to the TC
   - Swagger  (OpenAPI) Documentation providing guidance for client development
   - Tutorial for client implementation
- Compliance
   - Reference implementation with data of interested that can be use of useful tutorials
   - Executable test suite

**Comment by ingosimonis** [comment]
We develop a WCS RESTful API in Testbed-14 as part of the EOC-Swath task.
