### ISSUE TITLE
Implement a browser extension supporting MapML and the extended <map> element

### ISSUE THREAD

**Issue by prushforth** [opengeospatial/ideas#16]
MapML is a language for describing web maps, which has the goal of allowing browsers to implement map semantics in a similar way to that supported by other media types, such as audio and video through the &lt;audio&gt; and &lt;video&gt; elements in HTML.  

We should build a browser extension for chrome, firefox or other mainstream browser which could support Web pages which contain &lt;map&gt; elements, which would be a first step in getting such support built into browsers.

**Comment by ingosimonis** [comment]
Intensive client side processing of MapML is a task in Testbed-14. I close this item now. We need to revise MapML activities after the Testbed-14 report is out.
