### ISSUE TITLE
Advance client side form processing in MapML

### ISSUE THREAD

**Issue by prushforth** [opengeospatial/ideas#17]
Implement processing of &lt;form&gt; elements to support spatial + textual search in MapML.

For example:

&lt;mapml&gt;
&lt;head&gt;....&lt;/head&gt;
&lt;body&gt;
...
&lt;form action="https://example.com/maps/search"&gt;
&lt;input type="extent" name="qs"&gt;
&lt;input type="search" name="q"&gt;
&lt;button type="submit"&gt;&lt;/button&gt;
&lt;/form&gt;

&lt;/body&gt;
&lt;/mapml&gt;

**Comment by ingosimonis** [comment]
Intensive client side processing of MapML is a task in Testbed-14. I close this item now. We need to revise MapML activities after the Testbed-14 report is out.
