### ISSUE TITLE
Quality of Service Experience Part II - Investigate and define a test suite to assess and report on Web Service Quality of Experience

### ISSUE THREAD

**Issue by CindyMitchell** [opengeospatial/ideas#34]
Based on tested and validated recommendations for a quality web mapping service found in OGC Discussion Paper 17 - 049, investigate, define and develop a test suite that validates services for quality of experience parameters - the extent to which web mapping services meet best practices for cartographic representation, naming, etc., as per the suggested best practices in the discussion paper.

The draft discussion paper can be found at:
https://docs.google.com/document/d/13DCBYBR7t7AaZlRBIlPHSidoqt6xGJ0AERlBT4I0rM0/edit?usp=sharing

**Comment by ingosimonis** [comment]
Thank you, we included this issue in Testbed-14
