### ISSUE TITLE
Align MapML with other OGC standards.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ideas#36]
In the Testbed 13 a ER about MapML will document recommendations for aligning MapML with other OGC standards, including WMTS, WMS and OWS context and OpenSearch-GEO. This could result on the need for more testing in the future.

**Comment by prushforth** [comment]
Could we be specific, perhaps by creating issues in the [MapML repo](https://github.com/Maps4HTML/MapML), and inviting all / specific members of the various SWGs to comment and suggest alignments? I mean it would be great if people read the MapML spec AND the ER, but it may be easier to get them to address specific issues.  Also note I have created a MapML [![Join the chat at https://gitter.im/Maps4HTML/MapML](https://badges.gitter.im/Maps4HTML/MapML.svg)](https://gitter.im/Maps4HTML/MapML) for ease of discussion.  Thanks!
