### ISSUE TITLE
Create billable services

### ISSUE THREAD

**Issue by GabrielKepeklian** [opengeospatial/ideas#40]
# **Create billable services**
**_Normalize billing to facilitate the development of services for the valuation of EO data_**

What objectives?
•	Allow service providers to be adequately remunerated in order to develop their offer.
•	Enable users to compare service offerings based on EO.
•	Enable a competitive offer to grow.

Create billable services
The services designed on EO data are divided into B2B services and B2C services. B2C suppliers generally supply themselves from B2B suppliers (to which Atos belongs). At the OGC, the whole value chain is represented: the two categories B2B and B2C, to which must be added the final customers, whether they be administrations or companies. The billing is an essential component in the relationships and services delivered.
We know from experience that billing can be very complex. If one develops a service without initially foreseeing how it should be commercialized, if there are no specifications available to pass in a second time to a billable version, it is highly likely that the billing remains imperfect and that its development is difficult.
On the other hand, if one integrates it by construction during the design phase, aided by a standard, this secures it and increases the level of confidence of the market. Thus, the development of a B2B service taking into account billing will see its attractiveness increased, it also facilitates the work of the B2C supplier who will not have to develop the entire billing layer. He will already have a solid foundation. He will be able to develop his own services more quickly : his time to market will be shorter.
We propose to work on the definition of the B2B and B2C billing framework of services based on EO. The existence of this framework can prefigure a standard in OGC services billing.

**Comment by tomLandry** [comment]
I propose we seek commonalities and opportunities with https://github.com/opengeospatial/testbed14-ideas/issues/3. I think a federated cloud infrastructure is an important starting point for either free or billable services at regional, national and international levels. Billing and strong identity management goes hand in hand. Also, as noted in https://github.com/opengeospatial/testbed14-ideas/issues/3, emerging standards at NIST/IEEE will most probably cover billing. Also, note that TB-14 Earth Observation Clouds thread contained elements related to billable services, but my understanding is that these items will not be delivered in TB-13.

**Comment by pebau** [comment]
In particular for coverages billing is important, as they contribute much to the Big Data dilemma - and "shipping code to data" means that both access and processing should be billed. 
Let me propose to look at this in TB14 with emphasis on WCS and WCPS - their requests contain information for a policy-based billing.

**Comment by tomLandry** [comment]
Sounds great. Here, know that thought processes are started on the computing side (WPS, app packaging), but I'm not sure how much input I can/should provide here.
