### ISSUE TITLE
Prototype Quality of Service and Experience (QoSe) 

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ideas#6]
Prototype work being discussed at the Prototype Quality of Service and Experience (QoSe)  DWG
https://github.com/opengeospatial/QoSE-DWG

Advance rules to check that the metadata is created properly and better creating from the server (not catalog) and automatically populating a catalog.

**Comment by ingosimonis** [comment]
This is now addressed in Testbed-14's [Quality of Service and Experience](https://portal.opengeospatial.org/files/77327#QoSE) task.
